namespace StaticSiteGenerator
{
    public class CountryCodeLookup
    {
		public static string FullNameToIsoCode(string name)
		{
			switch (name)
			{
				case "Andorra": return "ad";
				case "United Arab Emirates": return "ae";
				case "Afghanistan": return "af";
				case "Antigua and Barbuda": return "ag";
				case "Anguilla": return "ai";
				case "Albania": return "al";
				case "Armenia": return "am";
				case "Angola": return "ao";
				case "Antarctica": return "aq";
				case "Argentina": return "ar";
				case "American Samoa": return "as";
				case "Austria": return "at";
				case "Australia": return "au";
				case "Aruba": return "aw";
				case "Åland Islands": return "ax";
				case "Azerbaijan": return "az";
				case "Bosnia and Herzegovina": return "ba";
				case "Barbados": return "bb";
				case "Bangladesh": return "bd";
				case "Belgium": return "be";
				case "Burkina Faso": return "bf";
				case "Bulgaria": return "bg";
				case "Bahrain": return "bh";
				case "Burundi": return "bi";
				case "Benin": return "bj";
				case "Saint Barthélemy": return "bl";
				case "Bermuda": return "bm";
				case "Brunei Darussalam": return "bn";
				case "Bolivia, Plurinational State of": return "bo";
				case "Bonaire, Sint Eustatius and Saba": return "bq";
				case "Brazil": return "br";
				case "Bahamas": return "bs";
				case "Bhutan": return "bt";
				case "Bouvet Island": return "bv";
				case "Botswana": return "bw";
				case "Belarus": return "by";
				case "Belize": return "bz";
				case "Canada": return "ca";
				case "Cocos (Keeling) Islands": return "cc";
				case "Congo, the Democratic Republic of the": return "cd";
				case "Central African Republic": return "cf";
				case "Congo": return "cg";
				case "Switzerland": return "ch";
				case "Côte d'Ivoire": return "ci";
				case "Cook Islands": return "ck";
				case "Chile": return "cl";
				case "Cameroon": return "cm";
				case "China": return "cn";
				case "Colombia": return "co";
				case "Costa Rica": return "cr";
				case "Cuba": return "cu";
				case "Cape Verde": return "cv";
				case "Curaçao": return "cw";
				case "Christmas Island": return "cx";
				case "Cyprus": return "cy";
				case "Czech Republic": return "cz";
				case "Germany": return "de";
				case "Djibouti": return "dj";
				case "Denmark": return "dk";
				case "Dominica": return "dm";
				case "Dominican Republic": return "do";
				case "Algeria": return "dz";
				case "Ecuador": return "ec";
				case "Estonia": return "ee";
				case "Egypt": return "eg";
				case "Western Sahara": return "eh";
				case "Eritrea": return "er";
				case "Spain": return "es";
				case "Ethiopia": return "et";
				case "Finland": return "fi";
				case "Fiji": return "fj";
				case "Falkland Islands (Malvinas)": return "fk";
				case "Micronesia, Federated States of": return "fm";
				case "Faroe Islands": return "fo";
				case "France": return "fr";
				case "Gabon": return "ga";
				case "United Kingdom": return "gb";
				case "England": return "gb";
				case "UK": return "gb";
				case "Grenada": return "gd";
				case "Georgia": return "ge";
				case "French Guiana": return "gf";
				case "Guernsey": return "gg";
				case "Ghana": return "gh";
				case "Gibraltar": return "gi";
				case "Greenland": return "gl";
				case "Gambia": return "gm";
				case "Guinea": return "gn";
				case "Guadeloupe": return "gp";
				case "Equatorial Guinea": return "gq";
				case "Greece": return "gr";
				case "South Georgia and the South Sandwich Islands": return "gs";
				case "Guatemala": return "gt";
				case "Guam": return "gu";
				case "Guinea-Bissau": return "gw";
				case "Guyana": return "gy";
				case "Hong Kong": return "hk";
				case "Heard Island and McDonald Islands": return "hm";
				case "Honduras": return "hn";
				case "Croatia": return "hr";
				case "Haiti": return "ht";
				case "Hungary": return "hu";
				case "Indonesia": return "id";
				case "Ireland": return "ie";
				case "Israel": return "il";
				case "Isle of Man": return "im";
				case "India": return "in";
				case "British Indian Ocean Territory": return "io";
				case "Iraq": return "iq";
				case "Iran, Islamic Republic of": return "ir";
				case "Iceland": return "is";
				case "Italy": return "it";
				case "Jersey": return "je";
				case "Jamaica": return "jm";
				case "Jordan": return "jo";
				case "Japan": return "jp";
				case "Kenya": return "ke";
				case "Kyrgyzstan": return "kg";
				case "Cambodia": return "kh";
				case "Kiribati": return "ki";
				case "Comoros": return "km";
				case "Saint Kitts and Nevis": return "kn";
				case "Korea, Democratic People's Republic of": return "kp";
				case "Korea, Republic of": return "kr";
				case "Kuwait": return "kw";
				case "Cayman Islands": return "ky";
				case "Kazakhstan": return "kz";
				case "Lao People's Democratic Republic": return "la";
				case "Lebanon": return "lb";
				case "Saint Lucia": return "lc";
				case "Liechtenstein": return "li";
				case "Sri Lanka": return "lk";
				case "Liberia": return "lr";
				case "Lesotho": return "ls";
				case "Lithuania": return "lt";
				case "Luxembourg": return "lu";
				case "Latvia": return "lv";
				case "Libya": return "ly";
				case "Morocco": return "ma";
				case "Monaco": return "mc";
				case "Moldova, Republic of": return "md";
				case "Montenegro": return "me";
				case "Saint Martin (French part)": return "mf";
				case "Madagascar": return "mg";
				case "Marshall Islands": return "mh";
				case "Macedonia, the former Yugoslav Republic of": return "mk";
				case "Mali": return "ml";
				case "Myanmar": return "mm";
				case "Mongolia": return "mn";
				case "Macao": return "mo";
				case "Northern Mariana Islands": return "mp";
				case "Martinique": return "mq";
				case "Mauritania": return "mr";
				case "Montserrat": return "ms";
				case "Malta": return "mt";
				case "Mauritius": return "mu";
				case "Maldives": return "mv";
				case "Malawi": return "mw";
				case "Mexico": return "mx";
				case "Malaysia": return "my";
				case "Mozambique": return "mz";
				case "Namibia": return "na";
				case "New Caledonia": return "nc";
				case "Niger": return "ne";
				case "Norfolk Island": return "nf";
				case "Nigeria": return "ng";
				case "Nicaragua": return "ni";
				case "Netherlands": return "nl";
				case "Norway": return "no";
				case "Nepal": return "np";
				case "Nauru": return "nr";
				case "Niue": return "nu";
				case "New Zealand": return "nz";
				case "Oman": return "om";
				case "Panama": return "pa";
				case "Peru": return "pe";
				case "French Polynesia": return "pf";
				case "Papua New Guinea": return "pg";
				case "Philippines": return "ph";
				case "Pakistan": return "pk";
				case "Poland": return "pl";
				case "Saint Pierre and Miquelon": return "pm";
				case "Pitcairn": return "pn";
				case "Puerto Rico": return "pr";
				case "Palestine, State of": return "ps";
				case "Portugal": return "pt";
				case "Palau": return "pw";
				case "Paraguay": return "py";
				case "Qatar": return "qa";
				case "Réunion": return "re";
				case "Romania": return "ro";
				case "Serbia": return "rs";
				case "Russian Federation": return "ru";
				case "Rwanda": return "rw";
				case "Saudi Arabia": return "sa";
				case "Solomon Islands": return "sb";
				case "Seychelles": return "sc";
				case "Sudan": return "sd";
				case "Sweden": return "se";
				case "Singapore": return "sg";
				case "Saint Helena, Ascension and Tristan da Cunha": return "sh";
				case "Slovenia": return "si";
				case "Svalbard and Jan Mayen": return "sj";
				case "Slovakia": return "sk";
				case "Sierra Leone": return "sl";
				case "San Marino": return "sm";
				case "Senegal": return "sn";
				case "Somalia": return "so";
				case "Suriname": return "sr";
				case "South Sudan": return "ss";
				case "Sao Tome and Principe": return "st";
				case "El Salvador": return "sv";
				case "Sint Maarten (Dutch part)": return "sx";
				case "Syrian Arab Republic": return "sy";
				case "Swaziland": return "sz";
				case "Turks and Caicos Islands": return "tc";
				case "Chad": return "td";
				case "French Southern Territories": return "tf";
				case "Togo": return "tg";
				case "Thailand": return "th";
				case "Tajikistan": return "tj";
				case "Tokelau": return "tk";
				case "Timor-Leste": return "tl";
				case "Turkmenistan": return "tm";
				case "Tunisia": return "tn";
				case "Tonga": return "to";
				case "Turkey": return "tr";
				case "Trinidad and Tobago": return "tt";
				case "Tuvalu": return "tv";
				case "Taiwan, Province of China": return "tw";
				case "Tanzania, United Republic of": return "tz";
				case "Ukraine": return "ua";
				case "Uganda": return "ug";
				case "United States Minor Outlying Islands": return "um";
				case "America": return "us";
				case "United States": return "us";
				case "USA": return "us";
				case "Uruguay": return "uy";
				case "Uzbekistan": return "uz";
				case "Saint Vincent and the Grenadines": return "vc";
				case "Venezuela, Bolivarian Republic of": return "ve";
				case "Virgin Islands, British": return "vg";
				case "Virgin Islands, U.S.": return "vi";
				case "Viet Nam": return "vn";
				case "Vanuatu": return "vu";
				case "Wallis and Futuna": return "wf";
				case "Samoa": return "ws";
				case "Yemen": return "ye";
				case "Mayotte": return "yt";
				case "South Africa": return "za";
				case "Zambia": return "zm";
				case "Zimbabwe": return "zw";

				default: return "none";
			}
		}
	}
}